### ISSUE TITLE
duplicated entities in response

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/Cosmos#102] opened 2020-04-10 13:24 UTC
It still seems that duplication of results is common. Example in current interface at time of posting. Search "infection rate" with defaults and go to equations. first result is duplicated. Same object, same reference.

<img width="820" alt="dup" src="https://user-images.githubusercontent.com/6107153/78993959-9b12af00-7b04-11ea-9eae-9f5cd1a42fd1.png">

**Comment by cambro** [comment] 2020-04-10 13:25
<img width="826" alt="dup" src="https://user-images.githubusercontent.com/6107153/78994053-d8773c80-7b04-11ea-97ce-8f47af99f233.png">

**Comment by davenquinn** [comment] 2020-04-10 18:00
Also found on [this page](http://cosmos.wisc.edu/sets/covid/?backend=Anserini&query=coronavirus%20lungs&type=Figure), along with figures apparently grouped with the wrong caption.

**Comment by iross** [comment] 2020-04-10 19:02
This isn't a bug in retrieval or the API. It's a user error in ingesting the data. The bottom line is that I accidentally put a small set of PDFs into the queue twice. We don't do duplicate checking on ingest, so I ended up doubling some of the results. Part of the issue is that I was doing separate runs on small piles of documents instead of one big run on the full pile (as the committed code would do it). 

The foreign keys don't cascade at the moment and making that change + yanking out the documents is too big a change for the live set at the moment.

We could also add pdf name (or pdf checksum) checks to make sure we don't ingest the same document more than once.

**Comment by cambro** [comment] 2020-04-19 17:06
@iross the DOI/GDD id should definitely be carried along all the way though every single thing that any of our applications do!

**Closed** 2020-05-21 16:43 UTC
Labels: API, bug
